name: Compile LaTeX
on: [push]
jobs:
  compile:
    name: Compile example document
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Fetch TeXLive Installer
      run: |
        wget "http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz"

    - name: Fix environment variables
      run: |
        echo "TEXLIVE_INSTALL_PREFIX=$HOME/texlive" >> $GITHUB_ENV
      shell: bash

    - name: Cache TeX Live
      id: cache-tex
      uses: actions/cache@v2
      with:
        path: ${{ env.TEXLIVE_INSTALL_PREFIX }}
        key: texlive-${{ hashFiles('install-tl-unx.tar.gz') }}

    - name: Install TeXLive
      if: steps.cache-tex.outputs.cache-hit != 'true'
      env:
        TEXLIVE_PROFILE_PATH: ${{ github.workspace }}/.github/texlive.profile
        TEXLIVE_PACKAGES_PATH: ${{ github.workspace }}/.github/texlive.packages
      run: |
        mkdir install-tl $TEXLIVE_INSTALL_PREFIX
        cat install-tl-unx.tar.gz | tar -xz -C install-tl --strip-components=1
        install-tl/install-tl --portable --profile "$TEXLIVE_PROFILE_PATH"
        readarray -t TEXLIVE_PACKAGES < "$TEXLIVE_PACKAGES_PATH"
        $TEXLIVE_INSTALL_PREFIX/bin/x86_64-linux/tlmgr install "${TEXLIVE_PACKAGES[@]}"

    - name: Set TeXLive PATH
      run: |
        echo "$TEXLIVE_INSTALL_PREFIX/bin/x86_64-linux" >> $GITHUB_PATH

    - name: Install svg2tikz
      run: |
        git clone https://github.com/xyz2tex/svg2tikz.git
        cd svg2tikz
        pip install .
        cd ..

    - name: Generate inner theme
      run: ./make_innertheme.sh

    - name: Compile PDF
      run: |
        texliveonfly example.tex >/dev/null 2>&1 || true
        ls example.pdf
